source 'https://rubygems.org'

ruby "2.3.1"

gem 'rack-attack', '~> 4.4.1'

gem "foreman", '~> 0.82'
gem "local_time", '~> 1.0'

gem 'rack-cors', :require => 'rack/cors'
# AMS
gem 'active_model_serializers', '~> 0.10.2'

gem 'sabisu_rails', github: "IcaliaLabs/sabisu-rails"

gem 'rails', '~> 4.2.7'

gem 'rails-html-sanitizer', '~> 1.0.3'


gem "awesome_print", '~> 1.7.0'
gem "font-awesome-rails", '~> 4.6.3'
gem 'bourbon', '~> 4.2.7'
gem 'neat', '~> 1.8.0'

gem 'uglifier', '~> 3.0.0'


gem 'jquery-rails', '~> 4.1.1'

gem 'devise', '~> 4.2.0'


gem 'sqlite3', '~> 1.3.13'
